import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import { Bold } from 'lucide-react';

const getPoppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-poppins',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(getPoppins.variable, 'antialiased')}>
        {children}
      </body>
    </html>
  );
}
